#!/usr/bin/env bash

# Wrapper script for Typo3 CLI tool.
# Must be run inside directory `typo3/sysext/core/bin` to avoid errors.

cd "${WEB_ROOT}"/typo3/sysext/core/bin || exit 1

php typo3 "$@"

cd ~- || exit 1
